cat ./java/org/eldarian/relay/*.java >> all_code.txt
cat ./java/org/eldarian/relay/controllers/*.java >> all_code.txt
cat ./java/org/eldarian/relay/entities/*.java >> all_code.txt
cat ./java/org/eldarian/relay/queries/*.java >> all_code.txt
cat ./java/org/eldarian/relay/queries/delete/*.java >> all_code.txt
cat ./java/org/eldarian/relay/queries/insert/*.java >> all_code.txt
cat ./java/org/eldarian/relay/queries/select/item/*.java >> all_code.txt
cat ./java/org/eldarian/relay/queries/select/list/*.java >> all_code.txt
cat ./java/org/eldarian/relay/queries/update/*.java >> all_code.txt
cat ./resources/static/style.css >> all_code.txt
cat ./resources/static/queries/*.sql >> all_code.txt
cat ./resources/static/queries/procedures/*.sql >> all_code.txt
cat ./resources/templates/*.html >> all_code.txt
cat ./resources/templates/addition/*.html >> all_code.txt
cat ./resources/templates/edition/*.html >> all_code.txt
cat ./resources/templates/general/*.html >> all_code.txt